### ISSUE TITLE
Very high ping when a player joins.

### ISSUE THREAD

**Issue by Adrip28** [ArkFlame/HamsterAPI#12] opened 2021-10-09 08:31 UTC
When a player connects, its ping gets about 6000ms and chunks won't load.

This occurs in 0.1.9 and 0.2.0

I'm using Paper 1.17.1 and Java 16.

I've user Paper builds 320 and 323

Hope you can fix it!

**Comment by linsaftw** [comment] 2021-10-09 15:39
Hello please send timings so we can identify the issue.

**Comment by Adrip28** [comment] 2021-10-09 21:26
https://timings.aikar.co/?id=f92a72ec15714eeab1a5b6e095a68231

**Comment by linsaftw** [comment] 2021-10-09 22:15
> https://timings.aikar.co/?id=f92a72ec15714eeab1a5b6e095a68231

Please send a longer timing of atleast 30 minutes. The one you sent only shows the first HamsterAPI join (which always lag because it has to prepare the classes) and then it shows 100% of the lag from chunks.

**Comment by linsaftw** [comment] 2021-10-10 01:16
I have tested with multiple players and detected lag during lot of joins. I will try my best to identify the cause of the error and fix it.

**Comment by Adrip28** [comment] 2021-10-15 16:50
Problem still happens in 2.0.1

I am getting the timings and will send them on when they are finished.

**Comment by Adrip28** [comment] 2021-10-15 17:10
Timings (2.0.1)

https://timings.aikar.co/d=17d2e26240ba46a293fb43914a15e3f1

**Comment by linsaftw** [comment] 2021-10-15 18:44
> Timings (2.0.1)
> 
> https://timings.aikar.co/d=17d2e26240ba46a293fb43914a15e3f1

404 not found

**Comment by linsaftw** [comment] 2021-10-15 21:53
fixed on a1c6c73

**Closed as completed by linsaftw** 2021-10-15 21:53 UTC
